### ISSUE TITLE
Database structure

### ISSUE THREAD

**Issue by kev007** [kev007/ARTFUL#1]
Create a database structure concept and create an empty implementation.

**Comment by pnancke** [comment]
The database structure is described in the [wiki](https://github.com/kev007/2016-FMdIR-Thema1/wiki/Database-structure) along with some sample data.

**Comment by kev007** [comment]
We should use "-" for year ranges instead of "_". The source corpora use this format, simplifying the parsing of the year from the file name.

Example:
"freq_2005-2011" instead of "freq_2005_2011"

**Comment by pnancke** [comment]
If I remember right, the character "-" is forbidden in column names.

**Comment by pnancke** [comment]
I think characters like "-" are forbidden in column names, but I'll check this out.

**Comment by kev007** [comment]
You are right! I forgot:

Only Alphanumeric characters and underline are allowed
The field name must begin with an alpha character or underline

**Comment by kev007** [comment]
Another question/concern:
Shouldn't our primary key be (word,language) since we want this pair to be unique? i.e. a word translation only once per language?

**Comment by pnancke** [comment]
Yes, your right. Will fix that tomorrow.

**Comment by pnancke** [comment]
Updated the database structure with a constraint on _(word, language)_. This removed 20.455 duplicate records.
