### ISSUE TITLE
Zwischenpräsentation

### ISSUE THREAD

**Issue by pnancke** [kev007/ARTFUL#28]
- Aufgabenstellung
- Architektur
  - DB
  - Spring
  - Leaflet
- Features
  - Screenshots der Anwendung
- Live Demo
- Ausblick 
  - Quotient anzeigen
  - gerichtete Beziehung zwischen Ländern
  - weitere Kategorien hinzufügen: Städte, Fußballer,...
- Probleme
  - keine vollständigen Korpora 
  - Kopora sind Sprachbezogen, nicht Länderbezogen
  - DBPedia 
  - SPARQL Einschränkungen

Treffen: Donnerstag 11:00 Uhr

**Comment by kev007** [comment]
https://docs.google.com/presentation/d/1xbvstpPIye9YdRi53FCmdYvl2omW1F4rhawNrTS8ekc/edit?usp=sharing
