### ISSUE TITLE
Put translations into the database

### ISSUE THREAD

**Issue by kev007** [kev007/ARTFUL#3]
W_ID, Country references,  (for all languages)
- Countries
- Cities / Metropolitan Areas
- States
- Heads of State

**Comment by dobraczka** [comment]
I've come up with a SPARQL query which gives back all cities over a certain population. Each city has a ID derived from dbo:wikiPageID. Also the rdfs:label of the city and the country it's located in is displayed in all languages that are available
The query is the following:

```
PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

select ?id ?nameLabel ?countryLabel
where {
?resource rdfs:label ?nameLabel .
?resource dbp:population ?population .
?resource dbo:wikiPageID ?id .
?resource dbo:country ?country .
?country rdfs:label ?countryLabel .
?resource dbo:location ?x
FILTER (?population >= 1000000 )
}
```

It could also be possible to make two queries: one to get only the cities in all languages and the other for the countries in all languages, but I think this way it's better, because the cities are already linked with the correct country.

(The query can be run [here](http://dbpedia.org/sparql))

**Comment by pnancke** [comment]
Are you sure the filter `?population >= 1000000` is applied? I do get countries with a smaller population as 1.000.000 e.g. "Brunei" with your query. But the translations for the countries work so far.

**Comment by dobraczka** [comment]
You're right, I also saw that the above query doesn't give the best results, but this one is much better:

```
PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT DISTINCT ?id ?citylabel ?countrylabel
WHERE { ?city rdf:type dbo:City ; 
              rdfs:label ?citylabel ; 
              dbo:country ?country ;
              dbo:populationTotal  ?population ;
              dbo:wikiPageID ?id .
        ?country rdfs:label ?countrylabel .
FILTER (?population >= 500000 )
}
```

(I've chosen 500.000 as threshold this time, but we can change it as we like)
Also to see just the URIs without all the translations the 'select' line can be changed to `SELECT DISTINCT ?id ?city ?country`

**Comment by pnancke** [comment]
Yeah, the query does the job now. Now it should be enough to just [load the data](http://dev.mysql.com/doc/refman/5.7/en/load-data.html) from the CSV or whatever into our database.

**Comment by dobraczka** [comment]
I've further refined the query:

```
PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT DISTINCT ?id ?citylabel ?locatedIn lang(?citylabel)
WHERE { ?city rdf:type dbo:City ; 
              rdfs:label ?citylabel ; 
              dbo:country ?locatedIn ;
              dbo:populationTotal  ?population ;
              dbo:wikiPageID ?id .
FILTER (?population >= 500000 )
}
```

This gives the id, name of the city,  which country the city is located in, language of the city name

**Comment by pnancke** [comment]
To get all translations from dbpedia: http://stackoverflow.com/questions/20937556/how-to-get-all-companies-from-dbpedia
