### ISSUE TITLE
Beautify the Ingoing/Outgoing References Radio Buttons

### ISSUE THREAD

**Issue by pnancke** [kev007/ARTFUL#45]
Beautify the Ingoing/Outgoing References Radio Buttons with a toggle switch or something else. Here are some examples: http://demos.jquerymobile.com/1.4.1/flipswitch/ Something else than jquery is also possible.

**Comment by kev007** [comment]
No need for a flipswitch. The GUI solution I am currently working on (design below) is hopefully more elegant:
![image](https://cloud.githubusercontent.com/assets/3058438/22301909/fc14d012-e32c-11e6-8c6f-a2a95176e388.png)

**Comment by pnancke** [comment]
Do whatever you like, I just don't like my current solution with the radio buttons. ;)

**Comment by pnancke** [comment]
The selected country has a different color for ingoing and outgoing mode (in outgoing mode the green is much darker, maybe there are two green layers?)
