### ISSUE TITLE
Only "de" and "en" languages in database

### ISSUE THREAD

**Issue by dobraczka** [kev007/ARTFUL#57]
Find out why only these 2 languages get transferred from csv to db

**Comment by kev007** [comment]
![image](https://cloud.githubusercontent.com/assets/3058438/22657642/7c7f6c44-ec97-11e6-8ca2-a6bc67a9c189.png)
The Leipzig Corpora Collection is rather large and was not uploaded to GitHub. Only 2 frequency lists, one for 'en' and one for 'de' are in the repository.
