### ISSUE TITLE
Strange logarithmic legend calculation when there is no data

### ISSUE THREAD

**Issue by kev007** [kev007/ARTFUL#75]
![image](https://cloud.githubusercontent.com/assets/3058438/23351419/4d743742-fcc1-11e6-991b-37ffdd766866.png)

**Comment by pnancke** [comment]
When does this happen?

**Comment by kev007** [comment]
When clicking on a country with 0 references
Example: China outgoing references

**Comment by kev007** [comment]
Example: Mongolia outgoing references
