### ISSUE TITLE
Uncaught TypeError when switching legend modes

### ISSUE THREAD

**Issue by kev007** [kev007/ARTFUL#76]
Don't know why the error is thrown. Everything still works?
![image](https://cloud.githubusercontent.com/assets/3058438/23351487/c0de3c46-fcc1-11e6-8331-9a91f4fed571.png)

**Comment by pnancke** [comment]
I dont get this error. How did u reproduce it?

**Comment by kev007** [comment]
Never mind. I found the cause: probably one of my chrome plugins :)
No error message with all extensions disabled.
