### ISSUE TITLE
The /freqs avgCorporaSize values are incorrect

### ISSUE THREAD

**Issue by kev007** [kev007/ARTFUL#80]
For example, Finland does not have a single corpus over the size of 1 million, yet:
[http://localhost:8080/freqs](http://localhost:8080/freqs)
`"avgCorporaSize":1775000,"name":"Finland","frequency":726`

Another example: in 2008 'deu' only has one corpus with a size of 1 million, yet:
[http://localhost:8080/freqs?start=2008&end=2008](http://localhost:8080/freqs?start=2008&end=2008)
`{"avgCorporaSize":800000,"name":"Germany","frequency":56974}`

I think this might be the average corpora size for the incoming references instead of the outgoing references.

**Comment by pnancke** [comment]
closed with #82
